site_name: 'City Data Model - Part 1: Foundation level concepts'
site_description: This ontology forms the basis of ISO/IEC 5087-1, which specifies
  the foundational level concepts for cities.
repo_url: https://github.com/ISO-TC204/ontology-cdm-p1-v1
nav:
- Home: index.md
- Untitled Ontology:
  - Acceleration (5087-1): classes/5087-1__Acceleration.md
  - Acceleration Unit (5087-1): classes/5087-1__AccelerationUnit.md
  - Activity (5087-1): classes/5087-1__Activity.md
  - Activity Status (5087-1): classes/5087-1__ActivityStatus.md
  - Activity Thing (5087-1): classes/5087-1__ActivityThing.md
  - Agent (5087-1): classes/5087-1__Agent.md
  - Agent Thing (5087-1): classes/5087-1__AgentThing.md
  - Agreement (5087-1): classes/5087-1__Agreement.md
  - Agreement Thing (5087-1): classes/5087-1__AgreementThing.md
  - Amount Of Money (5087-1): classes/5087-1__AmountOfMoney.md
  - Area (5087-1): classes/5087-1__Area.md
  - Area Unit (5087-1): classes/5087-1__AreaUnit.md
  - Atomic Agreement (5087-1): classes/5087-1__AtomicAgreement.md
  - Capacity (5087-1): classes/5087-1__Capacity.md
  - Capacity Size (5087-1): classes/5087-1__CapacitySize.md
  - Cardinality Measure (5087-1): classes/5087-1__CardinalityMeasure.md
  - Cardinality Unit Per Time (5087-1): classes/5087-1__CardinalityUnitPerTime.md
  - Cdm Thing (5087-1): classes/5087-1__CdmThing.md
  - Change Thing (5087-1): classes/5087-1__ChangeThing.md
  - City Units Thing (5087-1): classes/5087-1__CityUnitsThing.md
  - Complex Agreement (5087-1): classes/5087-1__ComplexAgreement.md
  - Conjunctive Agreement (5087-1): classes/5087-1__ConjunctiveAgreement.md
  - Conjunctive State (5087-1): classes/5087-1__ConjunctiveState.md
  - Consume State (5087-1): classes/5087-1__ConsumeState.md
  - Daily Recurring Event (5087-1): classes/5087-1__DailyRecurringEvent.md
  - Disjunctive Agreement (5087-1): classes/5087-1__DisjunctiveAgreement.md
  - Disjunctive State (5087-1): classes/5087-1__DisjunctiveState.md
  - Divisible Resource (5087-1): classes/5087-1__DivisibleResource.md
  - Duration (5087-1): classes/5087-1__Duration.md
  - Exception Day (5087-1): classes/5087-1__ExceptionDay.md
  - First Manifestation (5087-1): classes/5087-1__FirstManifestation.md
  - Foundational Cdm Thing (5087-1): classes/5087-1__FoundationalCdmThing.md
  - Geo_Position_unit (5087-1): classes/5087-1__Geo_Position_unit.md
  - Length (5087-1): classes/5087-1__Length.md
  - Length Unit (5087-1): classes/5087-1__LengthUnit.md
  - Location (5087-1): classes/5087-1__Location.md
  - Manifestation (5087-1): classes/5087-1__Manifestation.md
  - Manifestation State (5087-1): classes/5087-1__ManifestationState.md
  - Mass (5087-1): classes/5087-1__Mass.md
  - Mass Unit (5087-1): classes/5087-1__MassUnit.md
  - Monetary Value (5087-1): classes/5087-1__MonetaryValue.md
  - Monthly Recurring Event (5087-1): classes/5087-1__MonthlyRecurringEvent.md
  - Non Divisible Resource (5087-1): classes/5087-1__NonDivisibleResource.md
  - Non Terminal State (5087-1): classes/5087-1__NonTerminalState.md
  - Organization (5087-1): classes/5087-1__Organization.md
  - Organization Thing (5087-1): classes/5087-1__OrganizationThing.md
  - Planned Allocation (5087-1): classes/5087-1__PlannedAllocation.md
  - Produce State (5087-1): classes/5087-1__ProduceState.md
  - Ratio (5087-1): classes/5087-1__Ratio.md
  - Recurring Event (5087-1): classes/5087-1__RecurringEvent.md
  - Recurring Event Thing (5087-1): classes/5087-1__RecurringEventThing.md
  - Release State (5087-1): classes/5087-1__ReleaseState.md
  - Resource (5087-1): classes/5087-1__Resource.md
  - Resource Thing (5087-1): classes/5087-1__ResourceThing.md
  - Spatial Loc Thing (5087-1): classes/5087-1__SpatialLocThing.md
  - Speed (5087-1): classes/5087-1__Speed.md
  - Speed Unit (5087-1): classes/5087-1__SpeedUnit.md
  - State (5087-1): classes/5087-1__State.md
  - State Status (5087-1): classes/5087-1__StateStatus.md
  - Terminal Resource State (5087-1): classes/5087-1__TerminalResourceState.md
  - Terminal State (5087-1): classes/5087-1__TerminalState.md
  - Time Unit (5087-1): classes/5087-1__TimeUnit.md
  - Use State (5087-1): classes/5087-1__UseState.md
  - Value Of Money (5087-1): classes/5087-1__ValueOfMoney.md
  - Volume (5087-1): classes/5087-1__Volume.md
  - Volume Unit (5087-1): classes/5087-1__VolumeUnit.md
  - Weekly Recurring Event (5087-1): classes/5087-1__WeeklyRecurringEvent.md
  - Yearly Recurring Event (5087-1): classes/5087-1__YearlyRecurringEvent.md
site_url: https://isotc204.org/ontology-cdm-p1-v1
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/">
  <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank"
  rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
  src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img
  style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"
  alt=""></a></p>
theme:
  name: material
  features:
  - content.code.copy
  - content.status
  - content.tooltips
  - icons
  - navigation.path
  - navigation.top
  icon:
    repo: fontawesome/brands/github
    admonition:
      question: fontawesome/solid/comments
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra_css:
- stylesheets/extra.css
extra_javascript:
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- javascripts/tablesort.js
plugins:
- search
- git-revision-date-localized:
    type: date
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- md_in_html
- meta
- footnotes
- pymdownx.blocks.caption
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    base_path: docs
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: ''
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: true
extra:
  search:
    highlight: true
  hide:
  - title
  version:
    provider: mike
    alias: true
    default: latest
